// Task actionTypes
export const TASKS_FETCHED = 'TASKS_FETCHED';
export const TASK_MODIFIED = 'TASK_MODIFIED';
export const TASK_ADDED = 'TASK_ADDED';
export const TASK_OPERATION_LOADING = 'TASK_OPERATION_LOADING';
export const TASK_DELETION_SUCCESS = 'TASK_DELETION_SUCCESS';
export const TASK_OPERATION_ERROR = 'TASK_OPERATION_ERROR';

// Task List actionTypes
export const LIST_OPERATION_ERROR = 'LIST_OPERATION_ERROR';
export const LISTS_FETCHED = 'LISTS_FETCHED';
export const LIST_ADDED = 'LIST_ADDED';
export const LIST_OPERATION_LOADING = 'LIST_OPERATION_LOADING';
export const LIST_DELETION_SUCCESS = 'LIST_DELETION_SUCCESS';
export const LIST_MODIFIED = 'LIST_MODIFIED';

// General actionTypes
export const ERROR_ACKNOWLEDGED = 'ERROR_ACKNOWLEDGED';
