export const TASKS_FETCHED = 'TASKS_FETCHED';
export const TASK_MODIFIED = 'TASK_MODIFIED';
export const TASK_ADDED = 'TASK_ADDED';
export const TASK_OPERATION_LOADING = 'TASK_OPERATION_LOADING';
export const TASK_DELETION_SUCCESS = 'TASK_DELETION_SUCCESS';
export const TASK_OPERATION_ERROR = 'TASK_OPERATION_ERROR';
export const ERROR_ACKNOWLEDGED = 'ERROR_ACKNOWLEDGED';
